project:
  type: website

website:
  title: "{{< fa water >}} Covert Reef ðŸª¸"
  navbar:
    left:
      - href: proposal.qmd
        text: Proposal
        icon: files
      - href: datapre.qmd
        text: "{{< fa diagram-project >}} Methodology" 
      - text: Findings
        icon: journal-text
        menu: 
          - intro.qmd
          - tasks.qmd
      - href: poster.qmd
        text: "{{< fa file-powerpoint >}} Poster"
      - href: meeting_minutes.qmd
        text: Meeting Minutes
        icon: archive
    right:
      - href: about.qmd
        text: "{{< fa people-group >}} The Team"
      - text: "{{< fa laptop-code >}} Shiny App"
        menu:
        - href: user_guide.qmd
          text: ðŸŒŠ  User Guide  ðŸª¸
        - href: "https://dreytwy.shinyapps.io/VastChallengeCovertReef/"
          text: ðŸŒŠ  Shiny App  ðŸª¸
          target: _blank
      - icon: github
        text: Github
        menu: 
        - href: "https://github.com/JianyiLii/Group_Project-MC3"
          text: ðŸŒŠ  Project  ðŸª¸
          target: _blank
        - href: "https://github.com/JianyiLii/Shiny_CovertReef"
          text: ðŸŒŠ  Shiny  ðŸª¸
          target: _blank
          
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual
